#ifndef XRSERIALROVER_GLOBAL_H
#define XRSERIALROVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XRSERIALROVER_LIBRARY)
#  define XRSERIALROVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XRSERIALROVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XRSERIALROVER_GLOBAL_H

