#ifndef XRMAINWINDOW_GLOBAL_H
#define XRMAINWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XRMAINWINDOW_LIBRARY)
#  define XRMAINWINDOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XRMAINWINDOWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XRMAINWINDOW_GLOBAL_H

